# 1 numpy array 和 torch tensor 相互转换

In [1]:
import torch
import numpy as np

In [2]:
np_data = np.arange(6).reshape((2,3))

## 1.1 numpy array 转 torch tensor

In [3]:
torch_data = torch.from_numpy(np_data)

## 1.2 torch tensor 转 numpy array

In [4]:
tensor2array = torch_data.numpy()

In [5]:
print(
    '\nnumpy array:\n', np_data,
    '\ntorch tensor:\n', torch_data,  
    '\ntensor to array:\n', tensor2array, 
)


numpy array:
 [[0 1 2]
 [3 4 5]] 
torch tensor:
 tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32) 
tensor to array:
 [[0 1 2]
 [3 4 5]]


# 2 Torch 中的数学运算

## 2.1 绝对值计算

In [6]:
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data) # 转换成32位浮点tensor

In [7]:
print(
    '\nabs',
    '\nnumpy:', np.abs(data),
    '\ntorch:', torch.abs(tensor)
)


abs 
numpy: [1 2 1 2] 
torch: tensor([1., 2., 1., 2.])


## 2.2 三角函数

In [8]:
print(
    '\nsin',
    '\nnumpy:', np.sin(data),
    '\ntorch:', torch.sin(tensor))


sin 
numpy: [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch: tensor([-0.8415, -0.9093,  0.8415,  0.9093])


## 2.3 均值

In [9]:
print(
    '\nmean',
    '\nnumpy:', np.mean(data),
    '\ntorch:', torch.mean(tensor))


mean 
numpy: 0.0 
torch: tensor(0.)


## 2.4 矩阵点乘（dot product；scalar product；element-wise product）

In [10]:
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)

In [11]:
print(
    '\nmatrix dot product',
    '\nnumpy:\n', np.multiply(data, data),
    '\ntorch:\n', torch.mul(tensor, tensor))


matrix dot product 
numpy:
 [[ 1  4]
 [ 9 16]] 
torch:
 tensor([[ 1.,  4.],
        [ 9., 16.]])


## 2.5 矩阵叉乘（matrix multiplication；matrix product）

In [12]:
print(
    '\nmatrix multiplication',
    '\nnumpy:\n', np.matmul(data, data),
    '\ntorch:\n', torch.mm(tensor, tensor))


matrix multiplication 
numpy:
 [[ 7 10]
 [15 22]] 
torch:
 tensor([[ 7., 10.],
        [15., 22.]])
