In [1]:
import torch
from torch.autograd import Variable

# 定义Variable

In [2]:
tensor = torch.FloatTensor([[1,2], [3,4]])
variable = Variable(tensor, requires_grad=True) # requires_grad是参不参与误差反向传播，要不要计算梯度

In [3]:
print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


# Variable计算, 梯度

In [4]:
t_out = torch.mean(tensor * tensor)  # x^2
v_out = torch.mean(variable * variable)  # x^2，v_out = 1/4 * sum(variable*variable) 
print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward0>)


In [5]:
v_out.backward()  # 模型v_out的误差反向传播
print(variable.grad) # variable的梯度，d(v_out)/d(variable) = 1/4*2*variable = variable/2

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


# 获取Variable中的数据

直接 `print(variable)` 只会输出 Variable 形式的数据, 所以我们要转换一下, 将它变成 tensor 形式.

In [6]:
print(variable)     # variable 形式

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [7]:
print(variable.data) # tensor 形式

tensor([[1., 2.],
        [3., 4.]])


In [8]:
print(variable.data.numpy())  # numpy 形式

[[1. 2.]
 [3. 4.]]
